name: Ko Caller

on: 
  workflow_dispatch:
  push:
    tags:
      - "*" 

permissions: read-all

jobs:
  args:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ldflags.outputs.version }}
      something: ${{ steps.ldflags.outputs.something }}
    steps:
      - id: checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "::set-output name=version::v1.2.3"
          echo "::set-output name=something::something-fun"
          
  build:
    needs: args
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: NGUPP/slsa-github-generator-ko/blob/main/.github/workflows/slsa3-builder.yml@main
